// Built-in workflows. Each is a DAG of decision / task / outcome nodes (see engine.js for the format).
// Every decision node is ONE typed question that the Laya model answers; routing is plain data, so a workflow
// can be edited in the page's JSON editor without touching code. All example messages are synthetic.

export const WORKFLOWS = [
  {
    id: "support-triage",
    name: "Support ticket triage",
    domain: "Customer support",
    entity: "SupportTicket",
    description: "Classify a ticket, pick a priority, and either auto-reply, file it in the right queue, or page on-call.",
    input: { subject: true, key: "ticket" },
    start: "category",
    nodes: {
      category: {
        type: "decision", label: "What kind of request?",
        question: { type: "choice", instructions: "Which team should handle this ticket?", criteria: {
          bug: "Something is broken or not working", how_to: "A question about how to use the product",
          billing: "Charges, invoices, refunds or plans", account_access: "Login, password or account access" } },
        routes: { bug: "urgency", how_to: "send_article", billing: "billing_queue", account_access: "reset_link" },
        onLowConfidence: "human_triage",
      },
      urgency: {
        type: "decision", label: "How urgent is the bug?",
        question: { type: "score", instructions: "How urgent is this problem for the customer?", criteria: ["Can wait", "This week", "Today", "Right now"] },
        routes: { "0-1": "backlog", "2": "eng_queue", "3": "page_oncall" },
      },
      send_article: { type: "task", channel: "email", label: "Reply with help-center article", template: "Auto-reply to customer re: \"{{input.subject}}\" with the top help-center article.", next: "resolved" },
      reset_link: { type: "task", channel: "email", label: "Send secure reset link", template: "Send a password/2FA reset link for \"{{input.subject}}\".", next: "resolved" },
      billing_queue: { type: "task", channel: "ticket", label: "File in Billing queue", template: "Create billing ticket: {{input.subject}}", next: "billing_review" },
      backlog: { type: "task", channel: "ticket", label: "File bug in backlog", template: "Create P3 bug: {{input.subject}} (urgency {{answers.urgency.label}})", next: "filed" },
      eng_queue: { type: "task", channel: "ticket", label: "File P2 in Engineering", template: "Create P2 bug: {{input.subject}}", next: "filed" },
      page_oncall: { type: "task", channel: "page", label: "Page on-call engineer", template: "PAGE on-call: {{input.subject}}", next: "filed" },
      resolved: { type: "outcome", disposition: "auto", label: "Resolved automatically" },
      filed: { type: "outcome", disposition: "auto", label: "Routed automatically" },
      billing_review: { type: "outcome", disposition: "human", label: "Billing agent reviews" },
      human_triage: { type: "outcome", disposition: "human", label: "Human triage queue", detail: "Category unclear; an agent picks the team." },
    },
    examples: [
      { subject: "App crashes on launch", text: "Since the last update the app closes as soon as I open it. I have a client demo in one hour and nothing works!" },
      { subject: "How do I export to CSV?", text: "Hi, where can I find the option to export my reports as a CSV file? I looked in settings but couldn't see it." },
      { subject: "Charged twice", text: "I was billed twice for my monthly plan this month. Please refund the duplicate charge." },
      { subject: "Locked out", text: "I changed phones and now I can't get the two-factor code, so I can't log in to my account." },
      { subject: "Minor typo", text: "Small thing: the settings page says 'Prefrences' instead of 'Preferences'. No rush at all." },
      { subject: "Dashboard slow", text: "The dashboard has been loading slowly all week and sometimes the charts show an error. It's annoying but we can work around it for now." },
    ],
  },

  {
    id: "agent-guardrail",
    name: "AI agent action guardrail",
    domain: "AI safety",
    entity: "AgentAction",
    description: "Gate an action an autonomous agent wants to take. Fails closed: any risk signal stops the run.",
    input: {},
    start: "destructive",
    nodes: {
      destructive: {
        type: "decision", label: "Destructive / irreversible?",
        question: { type: "noul", instructions: "The action deletes, overwrites or changes data in a way that cannot be undone" },
        routes: { true: "block", false: "external" },
      },
      external: {
        type: "decision", label: "Touches money or the outside world?",
        question: { type: "noul", instructions: "The action sends money, emails or messages to people outside the company, or publishes something publicly" },
        routes: { true: "approval", false: "risk" },
      },
      risk: {
        type: "decision", label: "Overall risk",
        question: { type: "score", instructions: "How risky is it to let the agent do this without a human?", criteria: ["Low", "Medium", "High", "Critical"] },
        routes: { "0": "log_run", "1": "approval", "2+": "block" },
        onLowConfidence: "approval",
      },
      log_run: { type: "task", channel: "audit", label: "Write audit log entry", template: "Audit: agent action auto-approved.", next: "approved" },
      approval: { type: "task", channel: "chat", label: "Request approval in #agent-ops", template: "Approval requested for agent action.", next: "held" },
      block: { type: "task", channel: "audit", label: "Block and record reason", template: "Blocked agent action (destructive or high risk).", next: "blocked" },
      approved: { type: "outcome", disposition: "auto", label: "Approved, runs automatically" },
      held: { type: "outcome", disposition: "human", label: "Held for human approval" },
      blocked: { type: "outcome", disposition: "block", label: "Blocked" },
    },
    examples: [
      { text: "Agent plan: run DELETE FROM customers WHERE last_login < '2020-01-01' on the production database. No backup has been taken." },
      { text: "Agent plan: create a new git branch, apply the lint fixes, and open a draft pull request for review." },
      { text: "Agent plan: email the quarterly price increase announcement to all 12,000 customers on the mailing list." },
      { text: "Agent plan: read the last 50 lines of the application log file and summarize the errors." },
      { text: "Agent plan: transfer the remaining $4,800 marketing budget to the new vendor's account." },
      { text: "Agent plan: force-push the rewritten history to the main branch to remove the large files." },
    ],
  },

  {
    id: "incident-response",
    name: "IT incident response",
    domain: "Operations",
    entity: "Incident",
    description: "Turn a monitoring alert into an incident: rate severity, find the owning team, and decide whether to page and update the status page.",
    input: {},
    start: "severity",
    nodes: {
      severity: {
        type: "decision", label: "Severity",
        question: { type: "score", instructions: "How severe is this incident?", criteria: ["Minor", "Moderate", "Major", "Critical"] },
        routes: { "0-1": "ticket", "2-3": "impact" },
      },
      impact: {
        type: "decision", label: "Customers affected now?",
        question: { type: "noul", instructions: "Customers are affected by this problem right now" },
        routes: { true: "owner", false: "owner_quiet" },
        onLowConfidence: "owner",
      },
      owner: {
        type: "decision", label: "Owning team",
        question: { type: "choice", instructions: "Which team should own this incident?", criteria: {
          network: "Networking, DNS or load balancers", database: "Databases and storage", application: "Application code and services", security: "Security incident or attack" } },
        routes: { network: "page", database: "page", application: "page", security: "security_bridge" },
      },
      owner_quiet: {
        type: "decision", label: "Owning team (no impact)",
        question: { type: "choice", instructions: "Which team should own this incident?", criteria: {
          network: "Networking, DNS or load balancers", database: "Databases and storage", application: "Application code and services", security: "Security incident or attack" } },
        routes: { network: "ticket", database: "ticket", application: "ticket", security: "security_bridge" },
      },
      page: { type: "task", channel: "page", label: "Page owning team", template: "PAGE {{answers.owner.selected}} on-call (severity {{answers.severity.label}}).", next: "statuspage" },
      statuspage: { type: "task", channel: "webhook", label: "Post status-page update", template: "Status page: investigating degraded service.", next: "commander" },
      security_bridge: { type: "task", channel: "page", label: "Open security bridge", template: "Open security incident bridge; notify CISO.", next: "commander" },
      ticket: { type: "task", channel: "ticket", label: "Open incident ticket", template: "Create incident ticket (severity {{answers.severity.label}}).", next: "logged" },
      commander: { type: "outcome", disposition: "human", label: "Incident commander takes over" },
      logged: { type: "outcome", disposition: "auto", label: "Logged, no page" },
    },
    examples: [
      { text: "ALERT: checkout-api 5xx rate 42% for 10 minutes across all regions. Orders are failing for customers." },
      { text: "ALERT: disk usage on analytics-replica-3 at 81%, growing 1% per day." },
      { text: "ALERT: 3,000 failed SSH logins per minute from a single IP range against bastion hosts; two accounts now show successful logins." },
      { text: "ALERT: DNS resolution failing for api.example.com in eu-west; customer apps in Europe cannot reach the API." },
      { text: "ALERT: nightly report job took 14 minutes instead of the usual 9. Completed successfully." },
    ],
  },

  {
    id: "insurance-claim",
    name: "Insurance claim intake (FNOL)",
    domain: "Insurance",
    entity: "Claim",
    description: "First notice of loss: classify the claim, screen for injury and fraud signals, and fast-track simple claims.",
    input: {},
    start: "injury",
    nodes: {
      injury: {
        type: "decision", label: "Anyone injured?",
        question: { type: "noul", instructions: "Someone was injured or needed medical treatment" },
        routes: { true: "bodily_injury", false: "fraud" },
      },
      fraud: {
        type: "decision", label: "Fraud indicators?",
        question: { type: "noul", instructions: "The claim shows signs of possible fraud, such as inconsistent details, a very recent policy, or pressure to pay quickly in cash" },
        routes: { true: "siu", false: "claim_type" },
        onLowConfidence: "adjuster",
      },
      claim_type: {
        type: "decision", label: "Claim type",
        question: { type: "choice", instructions: "What type of claim is this?", criteria: {
          auto_glass: "Windshield or window glass damage only", auto_collision: "Vehicle collision damage", property_water: "Water damage to a home", theft: "Theft or burglary" } },
        routes: { auto_glass: "size", auto_collision: "adjuster", property_water: "size", theft: "police_report" },
      },
      size: {
        type: "decision", label: "Estimated loss size",
        question: { type: "score", instructions: "How large is the likely loss?", criteria: ["Under $1,000", "$1,000 to $5,000", "$5,000 to $25,000", "Over $25,000"] },
        routes: { "0-1": "fast_track", "2+": "adjuster" },
      },
      police_report: { type: "task", channel: "email", label: "Request police report number", template: "Ask claimant for the police report number.", next: "adjuster" },
      fast_track: { type: "task", channel: "webhook", label: "Straight-through payment", template: "Approve fast-track payment ({{answers.claim_type.selected}}, {{answers.size.label}}).", next: "paid" },
      siu: { type: "task", channel: "ticket", label: "Refer to Special Investigations", template: "SIU referral with fraud indicators.", next: "investigate" },
      bodily_injury: { type: "task", channel: "ticket", label: "Open bodily-injury file", template: "Open BI file; assign senior adjuster.", next: "senior" },
      adjuster: { type: "outcome", disposition: "human", label: "Assigned to adjuster" },
      senior: { type: "outcome", disposition: "human", label: "Senior injury adjuster" },
      investigate: { type: "outcome", disposition: "block", label: "Payment held pending SIU" },
      paid: { type: "outcome", disposition: "auto", label: "Paid automatically" },
    },
    examples: [
      { text: "A stone hit my windshield on the highway yesterday and left a long crack. Nobody was hurt. The glass shop quoted $420." },
      { text: "Rear-ended at a red light. My neck has been hurting since and I went to urgent care this morning." },
      { text: "A pipe burst under the kitchen sink and soaked the cabinets and floor. Plumber says repairs around $3,000." },
      { text: "My laptop and jewelry were stolen from my apartment last night; the door lock was broken." },
      { text: "I took out this policy last week. My car was totally destroyed in a fire yesterday, I have no photos, and I need the full $40,000 paid in cash by Friday." },
    ],
  },

  {
    id: "invoice-approval",
    name: "Invoice approval (AP)",
    domain: "Finance operations",
    entity: "Invoice",
    description: "Accounts-payable: check that an incoming invoice matches a purchase order, look for duplicates, and approve by amount tier.",
    input: {},
    start: "has_po",
    nodes: {
      has_po: {
        type: "decision", label: "References a purchase order?",
        question: { type: "noul", instructions: "The invoice references a purchase order number" },
        routes: { true: "duplicate", false: "request_po" },
      },
      duplicate: {
        type: "decision", label: "Possible duplicate?",
        question: { type: "noul", instructions: "This invoice may be a duplicate of one that was already sent or paid" },
        routes: { true: "dup_hold", false: "amount" },
        onLowConfidence: "ap_review",
      },
      amount: {
        type: "decision", label: "Amount tier",
        question: { type: "score", instructions: "How large is the invoice amount?", criteria: ["Under $1,000", "$1,000 to $10,000", "$10,000 to $50,000", "Over $50,000"] },
        routes: { "0-1": "schedule", "2": "manager", "3": "cfo" },
      },
      request_po: { type: "task", channel: "email", label: "Ask vendor for PO number", template: "Email vendor: please resend the invoice with a PO number.", next: "waiting" },
      schedule: { type: "task", channel: "webhook", label: "Schedule payment run", template: "Schedule for next payment run ({{answers.amount.label}}).", next: "approved" },
      manager: { type: "task", channel: "chat", label: "Request manager sign-off", template: "Manager sign-off needed ({{answers.amount.label}}).", next: "signoff" },
      cfo: { type: "task", channel: "chat", label: "Request CFO sign-off", template: "CFO sign-off needed ({{answers.amount.label}}).", next: "signoff" },
      dup_hold: { type: "task", channel: "ticket", label: "Hold as suspected duplicate", template: "Hold: suspected duplicate invoice.", next: "blocked" },
      approved: { type: "outcome", disposition: "auto", label: "Approved and scheduled" },
      signoff: { type: "outcome", disposition: "human", label: "Awaiting sign-off" },
      waiting: { type: "outcome", disposition: "human", label: "Waiting on vendor" },
      ap_review: { type: "outcome", disposition: "human", label: "AP clerk review" },
      blocked: { type: "outcome", disposition: "block", label: "Payment blocked" },
    },
    examples: [
      { text: "Invoice INV-2291 from Acme Office Supply for PO-7781: 40 boxes of printer paper, total $312.00, due in 30 days." },
      { text: "Invoice from Northwind Consulting for strategy workshop, total $48,500. No purchase order referenced." },
      { text: "REMINDER - second copy: Invoice INV-2291 from Acme Office Supply for PO-7781, total $312.00. Please pay again if not already processed." },
      { text: "Invoice 88-114 for PO-9001: annual data-center hosting contract, total $186,000." },
      { text: "Invoice INV-5520 for PO-4410: laptop docking stations, 25 units, total $6,125." },
    ],
  },

  {
    id: "refund-request",
    name: "Refund & returns",
    domain: "E-commerce",
    entity: "RefundRequest",
    description: "Decide whether a refund can be issued automatically, needs a return label first, or goes to a person.",
    input: {},
    start: "reason",
    nodes: {
      reason: {
        type: "decision", label: "Why a refund?",
        question: { type: "choice", instructions: "What is the main reason for the refund request?", criteria: {
          damaged: "Item arrived damaged or defective", not_received: "Order never arrived", changed_mind: "Customer changed their mind or it doesn't fit", wrong_item: "Wrong item was sent" } },
        routes: { damaged: "photo", not_received: "tracking", changed_mind: "window", wrong_item: "label" },
        onLowConfidence: "agent",
      },
      photo: {
        type: "decision", label: "Photo evidence given?",
        question: { type: "noul", instructions: "The customer says they have attached or can provide photos of the problem" },
        routes: { true: "refund", false: "ask_photo" },
      },
      window: {
        type: "decision", label: "Within 30 days?",
        question: { type: "noul", instructions: "The purchase was made within the last 30 days" },
        routes: { true: "label", false: "decline" },
        onLowConfidence: "agent",
      },
      tracking: { type: "task", channel: "webhook", label: "Check carrier tracking", template: "Query carrier API for tracking status.", next: "agent" },
      ask_photo: { type: "task", channel: "email", label: "Ask for a photo", template: "Ask customer for a photo of the damage.", next: "waiting" },
      label: { type: "task", channel: "email", label: "Send prepaid return label", template: "Email prepaid return label; refund on receipt.", next: "auto_done" },
      refund: { type: "task", channel: "webhook", label: "Issue refund", template: "Refund issued to original payment method.", next: "auto_done" },
      decline: { type: "task", channel: "email", label: "Explain return policy", template: "Explain 30-day policy; offer store credit.", next: "declined" },
      auto_done: { type: "outcome", disposition: "auto", label: "Handled automatically" },
      waiting: { type: "outcome", disposition: "human", label: "Waiting on customer" },
      agent: { type: "outcome", disposition: "human", label: "Support agent decides" },
      declined: { type: "outcome", disposition: "block", label: "Refund declined" },
    },
    examples: [
      { text: "The mug arrived shattered in the box. I've attached two photos of the broken pieces. Ordered it last week." },
      { text: "My order from three weeks ago still hasn't arrived and the tracking hasn't updated in ten days." },
      { text: "I bought these running shoes 5 days ago but they're half a size too small. Can I return them?" },
      { text: "I ordered a blue jacket and you sent me a red one." },
      { text: "I'd like to return the blender I bought four months ago, I just don't use it much." },
    ],
  },

  {
    id: "content-moderation",
    name: "Content moderation",
    domain: "Trust & safety",
    entity: "Post",
    description: "Publish, hold or remove a user comment. Only acts on its own when the model is confident.",
    input: {},
    start: "threat",
    nodes: {
      threat: {
        type: "decision", label: "Threat of violence?",
        question: { type: "noul", instructions: "The comment threatens violence or harm against a person" },
        routes: { true: "escalate", false: "spam" },
      },
      spam: {
        type: "decision", label: "Spam or ad?",
        question: { type: "noul", instructions: "The comment is spam or an unsolicited advertisement" },
        routes: { true: "remove", false: "toxicity" },
        onLowConfidence: "review",
      },
      toxicity: {
        type: "decision", label: "Toxicity",
        question: { type: "score", instructions: "How toxic or insulting is the language?", criteria: ["None", "Mild", "Strong", "Severe"] },
        routes: { "0": "publish", "1": "review", "2+": "remove" },
        onLowConfidence: "review",
      },
      escalate: { type: "task", channel: "page", label: "Escalate to safety team", template: "Escalate possible threat to the safety team.", next: "removed" },
      remove: { type: "task", channel: "webhook", label: "Remove post", template: "Remove post and notify author.", next: "removed" },
      publish: { type: "task", channel: "webhook", label: "Publish", template: "Publish comment.", next: "published" },
      published: { type: "outcome", disposition: "auto", label: "Published" },
      review: { type: "outcome", disposition: "human", label: "Moderator queue" },
      removed: { type: "outcome", disposition: "block", label: "Removed" },
    },
    examples: [
      { text: "Great write-up, thanks for sharing the setup details!" },
      { text: "BUY CHEAP FOLLOWERS NOW!!! 10k followers for $5, visit my profile link" },
      { text: "You are a complete idiot and everyone here knows it." },
      { text: "I know where you live and you'll regret posting this." },
      { text: "Honestly this take is pretty lazy, I expected better research." },
    ],
  },
];

export const WORKFLOW_BY_ID = Object.fromEntries(WORKFLOWS.map((w) => [w.id, w]));
